<?php

use Illuminate\Database\Seeder;

class RecipesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $recipes = [
            [
                'user_id' => 1,
                'category_id' => 1,
                'name' => 'Shake it Up! Pork Cutlets',
                'about' => "<h1 class=\"fela-y6xryt fela-o6evlq\" style=\"text-align: left; font-size: 32px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; line-height: 38px; color: rgb(52, 52, 52); font-family: Montserrat; letter-spacing: -0.3px; padding: 0px;\"><b><span style=\"font-family: &quot;Courier New&quot;;\">Shake it Up! Pork Cutlets</span></b></h1><h2 class=\"fela-gtjexx fela-1a517ak\" style=\"line-height: 32px; font-size: 24px; color: rgb(52, 52, 52); font-family: Montserrat; letter-spacing: -0.3px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px;\"><b><span style=\"font-family: &quot;Courier New&quot;;\">with Garlic Bread and an Apple and Sunflower Seed Salad</span></b></h2><p><span style=\"font-family: &quot;Source Sans Pro&quot;;\"><br></span></p><p><span style=\"font-family: &quot;Courier New&quot;;\">Although we can’t lay claim to the “put it in a bag and shake” method used to cook these pork cutlets, we’ll acknowledge that it’s pretty genius. That’s because it makes breading meat about as quick and easy as can be (and yes, it’s&nbsp;</span><em style=\"font-family: &quot;Source Sans Pro&quot;;\"><span style=\"font-family: &quot;Courier New&quot;;\">so</span></em><span style=\"font-family: &quot;Source Sans Pro&quot;;\"><span style=\"font-family: &quot;Courier New&quot;;\">&nbsp;</span><span style=\"font-family: &quot;Courier New&quot;;\">juicy). After it’s covered with breadcrumbs, the pork is fried in a pan ’til golden and served with toasted garlic bread and a crisp salad. If that sounds like a lot, fret not—this meal can be made in as little as 20 minutes.</span></span><br></p>",
                'ingredients' => "<p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">2 clove Garlic</p><p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">4 tablespoon Sour Cream</p><p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">2 tablespoon Fry Seasoning</p>",
                'preparation' => "<ol><li>Wash and dry all produce. Adjust rack to upper position and preheat oven to 450 degrees. Mince garlic. Place panko in a gallon-sized zip-close bag and season with salt and pepper (we used 2 tsp kosher salt).</li><li>Place sour cream in a medium bowl, then add pork and toss to coat. Place coated pork and fry seasoning in bag with panko and seal to close. Shake until pork is evenly coated. TIP: You may need to move around cutlets in bag, pressing with your hands to spread out panko and make it stick.</li><li>Heat a ¼-inch layer of oil in a large pan over medium-high heat (use a nonstick pan if you have one). Halve and core apples, then slice into thin half-moons. Thinly slice celery on a diagonal. Split ciabattas in half (as if you were making sandwiches).</li><li>Once oil is hot (it should sizzle if you add a breadcrumb), remove pork from bag (discard any panko that doesn’t stick). Add half the pork to pan and cook until panko is golden brown and crisp, 2-3 minutes per side. Transfer to a paper-towel-lined plate and set aside. Repeat with remaining pork.</li><li>Meanwhile, place 6 TBSP butter and garlic in a small, microwave-safe bowl. Microwave on high until butter melts, about 30 seconds. Place ciabatta halves cut-side up on a baking sheet and drizzle with butter mixture. Toast in oven until crisp and golden, about 5 minutes. Halve on a diagonal to create triangles.</li><li>While ciabattas toast, toss together apples, celery, arugula, sunflower seeds, 2 TBSP olive oil, and lemon juice to taste in a medium bowl. Season with salt and pepper. Divide pork, salad, and ciabattas between plates.<br></li></ol>",
                'slug' => str_slug('Shake it Up! Pork Cutlets')
            ],
            [
                'user_id' => 1,
                'category_id' => 2,
                'name' => 'Cherry Ancho Duck Breasts',
                'about' => "<h1 class=\"fela-y6xryt fela-o6evlq\" style=\"text-align: left; font-size: 32px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; line-height: 38px; color: rgb(52, 52, 52); font-family: Montserrat; letter-spacing: -0.3px; padding: 0px;\"><b><span style=\"font-family: &quot;Courier New&quot;;\">Shake it Up! Pork Cutlets</span></b></h1><h2 class=\"fela-gtjexx fela-1a517ak\" style=\"line-height: 32px; font-size: 24px; color: rgb(52, 52, 52); font-family: Montserrat; letter-spacing: -0.3px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px;\"><b><span style=\"font-family: &quot;Courier New&quot;;\">with Garlic Bread and an Apple and Sunflower Seed Salad</span></b></h2><p><span style=\"font-family: &quot;Source Sans Pro&quot;;\"><br></span></p><p><span style=\"font-family: &quot;Courier New&quot;;\">Although we can’t lay claim to the “put it in a bag and shake” method used to cook these pork cutlets, we’ll acknowledge that it’s pretty genius. That’s because it makes breading meat about as quick and easy as can be (and yes, it’s&nbsp;</span><em style=\"font-family: &quot;Source Sans Pro&quot;;\"><span style=\"font-family: &quot;Courier New&quot;;\">so</span></em><span style=\"font-family: &quot;Source Sans Pro&quot;;\"><span style=\"font-family: &quot;Courier New&quot;;\">&nbsp;</span><span style=\"font-family: &quot;Courier New&quot;;\">juicy). After it’s covered with breadcrumbs, the pork is fried in a pan ’til golden and served with toasted garlic bread and a crisp salad. If that sounds like a lot, fret not—this meal can be made in as little as 20 minutes.</span></span><br></p>",
                'ingredients' => "<p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">2 clove Garlic</p><p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">4 tablespoon Sour Cream</p><p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">2 tablespoon Fry Seasoning</p>",
                'preparation' => "<ol><li>Wash and dry all produce. Adjust rack to upper position and preheat oven to 450 degrees. Mince garlic. Place panko in a gallon-sized zip-close bag and season with salt and pepper (we used 2 tsp kosher salt).</li><li>Place sour cream in a medium bowl, then add pork and toss to coat. Place coated pork and fry seasoning in bag with panko and seal to close. Shake until pork is evenly coated. TIP: You may need to move around cutlets in bag, pressing with your hands to spread out panko and make it stick.</li><li>Heat a ¼-inch layer of oil in a large pan over medium-high heat (use a nonstick pan if you have one). Halve and core apples, then slice into thin half-moons. Thinly slice celery on a diagonal. Split ciabattas in half (as if you were making sandwiches).</li><li>Once oil is hot (it should sizzle if you add a breadcrumb), remove pork from bag (discard any panko that doesn’t stick). Add half the pork to pan and cook until panko is golden brown and crisp, 2-3 minutes per side. Transfer to a paper-towel-lined plate and set aside. Repeat with remaining pork.</li><li>Meanwhile, place 6 TBSP butter and garlic in a small, microwave-safe bowl. Microwave on high until butter melts, about 30 seconds. Place ciabatta halves cut-side up on a baking sheet and drizzle with butter mixture. Toast in oven until crisp and golden, about 5 minutes. Halve on a diagonal to create triangles.</li><li>While ciabattas toast, toss together apples, celery, arugula, sunflower seeds, 2 TBSP olive oil, and lemon juice to taste in a medium bowl. Season with salt and pepper. Divide pork, salad, and ciabattas between plates.<br></li></ol>",
                'slug' => str_slug('Cherry Ancho Duck Breasts')
            ],
            [
                'user_id' => 1,
                'category_id' => 1,
                'name' => 'Sausage Pizzas for Dinner',
                'about' => "<h1 class=\"fela-y6xryt fela-o6evlq\" style=\"text-align: left; font-size: 32px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; line-height: 38px; color: rgb(52, 52, 52); font-family: Montserrat; letter-spacing: -0.3px; padding: 0px;\"><b><span style=\"font-family: &quot;Courier New&quot;;\">Shake it Up! Pork Cutlets</span></b></h1><h2 class=\"fela-gtjexx fela-1a517ak\" style=\"line-height: 32px; font-size: 24px; color: rgb(52, 52, 52); font-family: Montserrat; letter-spacing: -0.3px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px;\"><b><span style=\"font-family: &quot;Courier New&quot;;\">with Garlic Bread and an Apple and Sunflower Seed Salad</span></b></h2><p><span style=\"font-family: &quot;Source Sans Pro&quot;;\"><br></span></p><p><span style=\"font-family: &quot;Courier New&quot;;\">Although we can’t lay claim to the “put it in a bag and shake” method used to cook these pork cutlets, we’ll acknowledge that it’s pretty genius. That’s because it makes breading meat about as quick and easy as can be (and yes, it’s&nbsp;</span><em style=\"font-family: &quot;Source Sans Pro&quot;;\"><span style=\"font-family: &quot;Courier New&quot;;\">so</span></em><span style=\"font-family: &quot;Source Sans Pro&quot;;\"><span style=\"font-family: &quot;Courier New&quot;;\">&nbsp;</span><span style=\"font-family: &quot;Courier New&quot;;\">juicy). After it’s covered with breadcrumbs, the pork is fried in a pan ’til golden and served with toasted garlic bread and a crisp salad. If that sounds like a lot, fret not—this meal can be made in as little as 20 minutes.</span></span><br></p>",
                'ingredients' => "<p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">2 clove Garlic</p><p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">4 tablespoon Sour Cream</p><p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">2 tablespoon Fry Seasoning</p>",
                'preparation' => "<ol><li>Wash and dry all produce. Adjust rack to upper position and preheat oven to 450 degrees. Mince garlic. Place panko in a gallon-sized zip-close bag and season with salt and pepper (we used 2 tsp kosher salt).</li><li>Place sour cream in a medium bowl, then add pork and toss to coat. Place coated pork and fry seasoning in bag with panko and seal to close. Shake until pork is evenly coated. TIP: You may need to move around cutlets in bag, pressing with your hands to spread out panko and make it stick.</li><li>Heat a ¼-inch layer of oil in a large pan over medium-high heat (use a nonstick pan if you have one). Halve and core apples, then slice into thin half-moons. Thinly slice celery on a diagonal. Split ciabattas in half (as if you were making sandwiches).</li><li>Once oil is hot (it should sizzle if you add a breadcrumb), remove pork from bag (discard any panko that doesn’t stick). Add half the pork to pan and cook until panko is golden brown and crisp, 2-3 minutes per side. Transfer to a paper-towel-lined plate and set aside. Repeat with remaining pork.</li><li>Meanwhile, place 6 TBSP butter and garlic in a small, microwave-safe bowl. Microwave on high until butter melts, about 30 seconds. Place ciabatta halves cut-side up on a baking sheet and drizzle with butter mixture. Toast in oven until crisp and golden, about 5 minutes. Halve on a diagonal to create triangles.</li><li>While ciabattas toast, toss together apples, celery, arugula, sunflower seeds, 2 TBSP olive oil, and lemon juice to taste in a medium bowl. Season with salt and pepper. Divide pork, salad, and ciabattas between plates.<br></li></ol>",
                'slug' => str_slug('Sausage Pizzas for Dinner')
            ],
            [
                'user_id' => 1,
                'category_id' => 1,
                'name' => 'Rib-Eye Steak Over Gruyère Mashed Potatoes',
                'about' => "<h1 class=\"fela-y6xryt fela-o6evlq\" style=\"text-align: left; font-size: 32px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; line-height: 38px; color: rgb(52, 52, 52); font-family: Montserrat; letter-spacing: -0.3px; padding: 0px;\"><b><span style=\"font-family: &quot;Courier New&quot;;\">Shake it Up! Pork Cutlets</span></b></h1><h2 class=\"fela-gtjexx fela-1a517ak\" style=\"line-height: 32px; font-size: 24px; color: rgb(52, 52, 52); font-family: Montserrat; letter-spacing: -0.3px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px;\"><b><span style=\"font-family: &quot;Courier New&quot;;\">with Garlic Bread and an Apple and Sunflower Seed Salad</span></b></h2><p><span style=\"font-family: &quot;Source Sans Pro&quot;;\"><br></span></p><p><span style=\"font-family: &quot;Courier New&quot;;\">Although we can’t lay claim to the “put it in a bag and shake” method used to cook these pork cutlets, we’ll acknowledge that it’s pretty genius. That’s because it makes breading meat about as quick and easy as can be (and yes, it’s&nbsp;</span><em style=\"font-family: &quot;Source Sans Pro&quot;;\"><span style=\"font-family: &quot;Courier New&quot;;\">so</span></em><span style=\"font-family: &quot;Source Sans Pro&quot;;\"><span style=\"font-family: &quot;Courier New&quot;;\">&nbsp;</span><span style=\"font-family: &quot;Courier New&quot;;\">juicy). After it’s covered with breadcrumbs, the pork is fried in a pan ’til golden and served with toasted garlic bread and a crisp salad. If that sounds like a lot, fret not—this meal can be made in as little as 20 minutes.</span></span><br></p>",
                'ingredients' => "<p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">2 clove Garlic</p><p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">4 tablespoon Sour Cream</p><p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">2 tablespoon Fry Seasoning</p>",
                'preparation' => "<ol><li>Wash and dry all produce. Adjust rack to upper position and preheat oven to 450 degrees. Mince garlic. Place panko in a gallon-sized zip-close bag and season with salt and pepper (we used 2 tsp kosher salt).</li><li>Place sour cream in a medium bowl, then add pork and toss to coat. Place coated pork and fry seasoning in bag with panko and seal to close. Shake until pork is evenly coated. TIP: You may need to move around cutlets in bag, pressing with your hands to spread out panko and make it stick.</li><li>Heat a ¼-inch layer of oil in a large pan over medium-high heat (use a nonstick pan if you have one). Halve and core apples, then slice into thin half-moons. Thinly slice celery on a diagonal. Split ciabattas in half (as if you were making sandwiches).</li><li>Once oil is hot (it should sizzle if you add a breadcrumb), remove pork from bag (discard any panko that doesn’t stick). Add half the pork to pan and cook until panko is golden brown and crisp, 2-3 minutes per side. Transfer to a paper-towel-lined plate and set aside. Repeat with remaining pork.</li><li>Meanwhile, place 6 TBSP butter and garlic in a small, microwave-safe bowl. Microwave on high until butter melts, about 30 seconds. Place ciabatta halves cut-side up on a baking sheet and drizzle with butter mixture. Toast in oven until crisp and golden, about 5 minutes. Halve on a diagonal to create triangles.</li><li>While ciabattas toast, toss together apples, celery, arugula, sunflower seeds, 2 TBSP olive oil, and lemon juice to taste in a medium bowl. Season with salt and pepper. Divide pork, salad, and ciabattas between plates.<br></li></ol>",
                'slug' => str_slug('Rib-Eye Steak Over Gruyère Mashed Potatoes')
            ],
            [
                'user_id' => 1,
                'category_id' => 1,
                'name' => 'Spanish One-Pan Chicken',
                'about' => "<h1 class=\"fela-y6xryt fela-o6evlq\" style=\"text-align: left; font-size: 32px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; line-height: 38px; color: rgb(52, 52, 52); font-family: Montserrat; letter-spacing: -0.3px; padding: 0px;\"><b><span style=\"font-family: &quot;Courier New&quot;;\">Shake it Up! Pork Cutlets</span></b></h1><h2 class=\"fela-gtjexx fela-1a517ak\" style=\"line-height: 32px; font-size: 24px; color: rgb(52, 52, 52); font-family: Montserrat; letter-spacing: -0.3px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px;\"><b><span style=\"font-family: &quot;Courier New&quot;;\">with Garlic Bread and an Apple and Sunflower Seed Salad</span></b></h2><p><span style=\"font-family: &quot;Source Sans Pro&quot;;\"><br></span></p><p><span style=\"font-family: &quot;Courier New&quot;;\">Although we can’t lay claim to the “put it in a bag and shake” method used to cook these pork cutlets, we’ll acknowledge that it’s pretty genius. That’s because it makes breading meat about as quick and easy as can be (and yes, it’s&nbsp;</span><em style=\"font-family: &quot;Source Sans Pro&quot;;\"><span style=\"font-family: &quot;Courier New&quot;;\">so</span></em><span style=\"font-family: &quot;Source Sans Pro&quot;;\"><span style=\"font-family: &quot;Courier New&quot;;\">&nbsp;</span><span style=\"font-family: &quot;Courier New&quot;;\">juicy). After it’s covered with breadcrumbs, the pork is fried in a pan ’til golden and served with toasted garlic bread and a crisp salad. If that sounds like a lot, fret not—this meal can be made in as little as 20 minutes.</span></span><br></p>",
                'ingredients' => "<p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">2 clove Garlic</p><p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">4 tablespoon Sour Cream</p><p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">2 tablespoon Fry Seasoning</p>",
                'preparation' => "<ol><li>Wash and dry all produce. Adjust rack to upper position and preheat oven to 450 degrees. Mince garlic. Place panko in a gallon-sized zip-close bag and season with salt and pepper (we used 2 tsp kosher salt).</li><li>Place sour cream in a medium bowl, then add pork and toss to coat. Place coated pork and fry seasoning in bag with panko and seal to close. Shake until pork is evenly coated. TIP: You may need to move around cutlets in bag, pressing with your hands to spread out panko and make it stick.</li><li>Heat a ¼-inch layer of oil in a large pan over medium-high heat (use a nonstick pan if you have one). Halve and core apples, then slice into thin half-moons. Thinly slice celery on a diagonal. Split ciabattas in half (as if you were making sandwiches).</li><li>Once oil is hot (it should sizzle if you add a breadcrumb), remove pork from bag (discard any panko that doesn’t stick). Add half the pork to pan and cook until panko is golden brown and crisp, 2-3 minutes per side. Transfer to a paper-towel-lined plate and set aside. Repeat with remaining pork.</li><li>Meanwhile, place 6 TBSP butter and garlic in a small, microwave-safe bowl. Microwave on high until butter melts, about 30 seconds. Place ciabatta halves cut-side up on a baking sheet and drizzle with butter mixture. Toast in oven until crisp and golden, about 5 minutes. Halve on a diagonal to create triangles.</li><li>While ciabattas toast, toss together apples, celery, arugula, sunflower seeds, 2 TBSP olive oil, and lemon juice to taste in a medium bowl. Season with salt and pepper. Divide pork, salad, and ciabattas between plates.<br></li></ol>",
                'slug' => str_slug('Spanish One-Pan Chicken')
            ],
            [
                'user_id' => 1,
                'category_id' => 1,
                'name' => 'Figgy Balsamic Chicken Legs',
                'about' => "<h1 class=\"fela-y6xryt fela-o6evlq\" style=\"text-align: left; font-size: 32px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; line-height: 38px; color: rgb(52, 52, 52); font-family: Montserrat; letter-spacing: -0.3px; padding: 0px;\"><b><span style=\"font-family: &quot;Courier New&quot;;\">Shake it Up! Pork Cutlets</span></b></h1><h2 class=\"fela-gtjexx fela-1a517ak\" style=\"line-height: 32px; font-size: 24px; color: rgb(52, 52, 52); font-family: Montserrat; letter-spacing: -0.3px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px;\"><b><span style=\"font-family: &quot;Courier New&quot;;\">with Garlic Bread and an Apple and Sunflower Seed Salad</span></b></h2><p><span style=\"font-family: &quot;Source Sans Pro&quot;;\"><br></span></p><p><span style=\"font-family: &quot;Courier New&quot;;\">Although we can’t lay claim to the “put it in a bag and shake” method used to cook these pork cutlets, we’ll acknowledge that it’s pretty genius. That’s because it makes breading meat about as quick and easy as can be (and yes, it’s&nbsp;</span><em style=\"font-family: &quot;Source Sans Pro&quot;;\"><span style=\"font-family: &quot;Courier New&quot;;\">so</span></em><span style=\"font-family: &quot;Source Sans Pro&quot;;\"><span style=\"font-family: &quot;Courier New&quot;;\">&nbsp;</span><span style=\"font-family: &quot;Courier New&quot;;\">juicy). After it’s covered with breadcrumbs, the pork is fried in a pan ’til golden and served with toasted garlic bread and a crisp salad. If that sounds like a lot, fret not—this meal can be made in as little as 20 minutes.</span></span><br></p>",
                'ingredients' => "<p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">2 clove Garlic</p><p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">4 tablespoon Sour Cream</p><p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">2 tablespoon Fry Seasoning</p>",
                'preparation' => "<ol><li>Wash and dry all produce. Adjust rack to upper position and preheat oven to 450 degrees. Mince garlic. Place panko in a gallon-sized zip-close bag and season with salt and pepper (we used 2 tsp kosher salt).</li><li>Place sour cream in a medium bowl, then add pork and toss to coat. Place coated pork and fry seasoning in bag with panko and seal to close. Shake until pork is evenly coated. TIP: You may need to move around cutlets in bag, pressing with your hands to spread out panko and make it stick.</li><li>Heat a ¼-inch layer of oil in a large pan over medium-high heat (use a nonstick pan if you have one). Halve and core apples, then slice into thin half-moons. Thinly slice celery on a diagonal. Split ciabattas in half (as if you were making sandwiches).</li><li>Once oil is hot (it should sizzle if you add a breadcrumb), remove pork from bag (discard any panko that doesn’t stick). Add half the pork to pan and cook until panko is golden brown and crisp, 2-3 minutes per side. Transfer to a paper-towel-lined plate and set aside. Repeat with remaining pork.</li><li>Meanwhile, place 6 TBSP butter and garlic in a small, microwave-safe bowl. Microwave on high until butter melts, about 30 seconds. Place ciabatta halves cut-side up on a baking sheet and drizzle with butter mixture. Toast in oven until crisp and golden, about 5 minutes. Halve on a diagonal to create triangles.</li><li>While ciabattas toast, toss together apples, celery, arugula, sunflower seeds, 2 TBSP olive oil, and lemon juice to taste in a medium bowl. Season with salt and pepper. Divide pork, salad, and ciabattas between plates.<br></li></ol>",
                'slug' => str_slug('Figgy Balsamic Chicken Legs')
            ],
            [
                'user_id' => 1,
                'category_id' => 1,
                'name' => 'Chicken Milanese with Crispy Potatoes, Mixed Greens, and Creamy Lemon-Chive Dressing',
                'about' => "<h1 class=\"fela-y6xryt fela-o6evlq\" style=\"text-align: left; font-size: 32px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; line-height: 38px; color: rgb(52, 52, 52); font-family: Montserrat; letter-spacing: -0.3px; padding: 0px;\"><b><span style=\"font-family: &quot;Courier New&quot;;\">Shake it Up! Pork Cutlets</span></b></h1><h2 class=\"fela-gtjexx fela-1a517ak\" style=\"line-height: 32px; font-size: 24px; color: rgb(52, 52, 52); font-family: Montserrat; letter-spacing: -0.3px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px;\"><b><span style=\"font-family: &quot;Courier New&quot;;\">with Garlic Bread and an Apple and Sunflower Seed Salad</span></b></h2><p><span style=\"font-family: &quot;Source Sans Pro&quot;;\"><br></span></p><p><span style=\"font-family: &quot;Courier New&quot;;\">Although we can’t lay claim to the “put it in a bag and shake” method used to cook these pork cutlets, we’ll acknowledge that it’s pretty genius. That’s because it makes breading meat about as quick and easy as can be (and yes, it’s&nbsp;</span><em style=\"font-family: &quot;Source Sans Pro&quot;;\"><span style=\"font-family: &quot;Courier New&quot;;\">so</span></em><span style=\"font-family: &quot;Source Sans Pro&quot;;\"><span style=\"font-family: &quot;Courier New&quot;;\">&nbsp;</span><span style=\"font-family: &quot;Courier New&quot;;\">juicy). After it’s covered with breadcrumbs, the pork is fried in a pan ’til golden and served with toasted garlic bread and a crisp salad. If that sounds like a lot, fret not—this meal can be made in as little as 20 minutes.</span></span><br></p>",
                'ingredients' => "<p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">2 clove Garlic</p><p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">4 tablespoon Sour Cream</p><p class=\"fela-2htk9c\" style=\"margin-bottom: 0px; line-height: 1.7; font-family: &quot;Source Sans Pro&quot;; font-size: 14px;\">2 tablespoon Fry Seasoning</p>",
                'preparation' => "<ol><li>Wash and dry all produce. Adjust rack to upper position and preheat oven to 450 degrees. Mince garlic. Place panko in a gallon-sized zip-close bag and season with salt and pepper (we used 2 tsp kosher salt).</li><li>Place sour cream in a medium bowl, then add pork and toss to coat. Place coated pork and fry seasoning in bag with panko and seal to close. Shake until pork is evenly coated. TIP: You may need to move around cutlets in bag, pressing with your hands to spread out panko and make it stick.</li><li>Heat a ¼-inch layer of oil in a large pan over medium-high heat (use a nonstick pan if you have one). Halve and core apples, then slice into thin half-moons. Thinly slice celery on a diagonal. Split ciabattas in half (as if you were making sandwiches).</li><li>Once oil is hot (it should sizzle if you add a breadcrumb), remove pork from bag (discard any panko that doesn’t stick). Add half the pork to pan and cook until panko is golden brown and crisp, 2-3 minutes per side. Transfer to a paper-towel-lined plate and set aside. Repeat with remaining pork.</li><li>Meanwhile, place 6 TBSP butter and garlic in a small, microwave-safe bowl. Microwave on high until butter melts, about 30 seconds. Place ciabatta halves cut-side up on a baking sheet and drizzle with butter mixture. Toast in oven until crisp and golden, about 5 minutes. Halve on a diagonal to create triangles.</li><li>While ciabattas toast, toss together apples, celery, arugula, sunflower seeds, 2 TBSP olive oil, and lemon juice to taste in a medium bowl. Season with salt and pepper. Divide pork, salad, and ciabattas between plates.<br></li></ol>",
                'slug' => str_slug('Chicken Milanese with Crispy Potatoes, Mixed Greens, and Creamy Lemon-Chive Dressing')
            ]
        ];

        foreach ($recipes as $recipe) {
            \App\Recipe::create($recipe);
        }
    }
}
